 package yadihar;

import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class akutansi extends javax.swing.JFrame {

  
private void kosong(){
    // mengosongkan tiap jtexfild,setelah statemen input data
    
    
    
  //txtNo_Pembayaran.setText(null);  
   txtNamaBarang.setText(null);
  txtHarga.setText(null);
  txtQty_Rcv.setText(null);
  txtPassed.setText(null);
  txtTotal.setText(null);
   
    }
private void tampilkan_data(){
    //membuat nama nama pada tiap kolom jtable
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No Pembayaran");
    model.addColumn("kode ");
    model.addColumn("Nama_Barang");
    model.addColumn("Harga");
    model.addColumn("Qty_Rcv");
    model.addColumn("Passed");
    model.addColumn("Total");
   
    //menampilkan datadari database ke dalam tabel
    try{ //MEMBUAT VARIABEL NOMOR  ( memanggil data dari dtabase)
        int no = 1; // untuk memberi urutan nilai 1 dan seterusnya
        String sql ="SELECT *from akutansi"; // cari dari string cari
        java.sql.Connection conn = (Connection)konfig.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        while(res.next()){
            model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
         }
        tabel.setModel(model);
        
    }catch (SQLException e){
        System.out.println("Error" + e.getMessage());
    }
    }

private  void tampil(){
    //meengambil dan menampilkan data dari database (dari Queri kode jcombobok)
         if (Kode.getSelectedItem().equals("pilih barang")){
            txtNamaBarang.setText("");
            txtQty_Rcv.setText("");
        }else{
            try {
                Connection c = konfig.configDB();
                Statement s = c.createStatement();

                String sql = "SELECT Nama_Barang, Qty_Rcv FROM receiver_po WHERE Kode ='" + Kode .getSelectedItem() + "'";
                ResultSet r = s.executeQuery(sql);

                while (r.next()) {
                    txtNamaBarang.setText(r.getString("Nama_Barang"));
                     txtQty_Rcv.setText (r.getString("Qty_Rcv"));
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

}


    /**
     * Creates new form akutansi
     */
    public akutansi() {
        initComponents();
        kosong();
        tampilkan_data();
        tampilpilih();
    }

    private void tampilpilih() {
        //menampilkan data barang dari jcombobox
        try {
            Connection c = konfig.configDB();
            Statement s = c.createStatement();
            String sql = "SELECT Kode FROM receiver_po ORDER BY Kode asc";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                Kode.addItem(r.getString("Kode"));
            }
            r.last();
            int jumlahdata = r.getRow();
            r.first();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }   
    }

        
            public void FilterHuruf(KeyEvent a){
       if(Character.isDigit(a.getKeyChar())){
           a.consume();
           JOptionPane.showMessageDialog(null, "masukan huruf saja!", "peringatan", JOptionPane.WARNING_MESSAGE);
       }
    }
    public void FilterAngka(KeyEvent a){
       if(Character.isAlphabetic(a.getKeyChar())){
           a.consume();
           JOptionPane.showMessageDialog(null, "masukan angka saja!", "peringatan", JOptionPane.WARNING_MESSAGE);
       }
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassed = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtQty_Rcv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        Kode = new javax.swing.JComboBox();
        txtTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNo_Pembayaran = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEM INFORMASI AKUTANSI");

        jLabel2.setText("Kode");

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Harga");

        txtPassed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassedActionPerformed(evt);
            }
        });
        txtPassed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassedKeyPressed(evt);
            }
        });

        txtNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBarangActionPerformed(evt);
            }
        });

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        jLabel5.setText("Qty_Rcv");

        txtQty_Rcv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQty_RcvKeyPressed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setToolTipText("");
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        Kode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pilih Barang" }));
        Kode.setActionCommand("Kode");
        Kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeActionPerformed(evt);
            }
        });

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        jLabel6.setText("Total");

        jLabel7.setText("No Transaksi");

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Passed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtQty_Rcv, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 337, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNo_Pembayaran)
                                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(Kode, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPassed, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(simpan)
                        .addGap(120, 120, 120)
                        .addComponent(tambah))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNo_Pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQty_Rcv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(tambah))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
         kosong();
        tambah.setEnabled(true);
        simpan.setEnabled(true);
    
    }//GEN-LAST:event_tambahActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
          if(Kode.getSelectedItem().equals("") || txtNamaBarang.getText().equals("") || txtHarga.getText().equals("")|| txtQty_Rcv.getText().equals("")|| txtPassed.getText().equals("") || txtTotal.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Data", "manajament system", JOptionPane.INFORMATION_MESSAGE);
        }else{
            String no_pembayaran =  txtNo_Pembayaran.getText();
            String kode = (String) Kode.getSelectedItem();
            String NmBrng = txtNamaBarang.getText();
            String hrg = txtHarga.getText();
            String qty = txtQty_Rcv.getText();
            String passed = txtPassed.getText();
            String total = txtTotal.getText();
            try{
                Connection c = konfig.configDB();
                String sql="Insert into akutansi values (?,?,?,?,?,?,?)";
                PreparedStatement p=(PreparedStatement)c.prepareStatement(sql);
                p.setString(1,no_pembayaran);
                p.setString(2,kode);
                p.setString(3,NmBrng);
                p.setString(4,hrg);
                p.setString(5,qty );
                p.setString(6,passed);
                p.setString(7,total);
                p.executeUpdate();
                p.close();
            
            
            
            }catch(SQLException e){
                System.out.println(e);
            }finally{
                tampilkan_data();
                JOptionPane.showMessageDialog(this,"Data Telah Tersimpan");
               
               kosong();
                }
        } 
    }//GEN-LAST:event_simpanActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
      tambah.setEnabled(true);
      simpan.setEnabled(true);
            

// TODO add your handling code here:
        int baris = tabel.rowAtPoint(evt.getPoint());
        
         String no_bayar = tabel.getValueAt(baris,0).toString();
        txtNo_Pembayaran.setText(no_bayar);
        
        String kode = tabel.getValueAt(baris, 1).toString();
        Kode.setSelectedItem(kode);
        
        String namabarang= tabel.getValueAt(baris, 2).toString();
        txtNamaBarang.setText(namabarang);
        
        String harga = tabel.getValueAt(baris, 3).toString();
        txtHarga.setText(harga);
        
        String qty_rcv =  tabel.getValueAt(baris, 4).toString();
        txtQty_Rcv.setText(qty_rcv);
        
        String Passed = tabel.getValueAt(baris, 5).toString();
        txtPassed.setText(Passed);
        
        String total = tabel.getValueAt(baris,6).toString();
        txtTotal.setText(total);
        
       
    }//GEN-LAST:event_tabelMouseClicked

    private void KodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeActionPerformed
        // pemangilan data dari data base
        if (Kode.getSelectedItem().equals("pilih barang")){
            txtNamaBarang.setText("");
            txtQty_Rcv.setText("");
        }else{
            try {
                Connection c = konfig.configDB();
                Statement s = c.createStatement();

                String sql = "SELECT Nama_Barang,Qty_Rcv FROM receiver_po WHERE Kode ='" + Kode.getSelectedItem() + "'";
                ResultSet r = s.executeQuery(sql);

                while (r.next()) {
                   txtNamaBarang.setText(r.getString("Nama_Barang"));
                   txtQty_Rcv.setText(r.getString("Qty_Rcv"));
                     }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_KodeActionPerformed

    private void txtQty_RcvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQty_RcvKeyPressed
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_txtQty_RcvKeyPressed

    private void txtPassedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassedActionPerformed

    private void txtPassedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassedKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtQty_Rcv.getText().equals("") || txtHarga.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Data", "TK. Sinar Abadi", JOptionPane.INFORMATION_MESSAGE);
            }else{
                String a = txtQty_Rcv.getText();
                int aa = Integer.parseInt(a);
                String b = txtQty_Rcv.getText();
                int bb = Integer.parseInt(b);
                if(aa > bb){
                    JOptionPane.showMessageDialog(null, "Jumlah beli melebihi Stok yang Ada " + bb, "TK. Abadi Jaya", JOptionPane.INFORMATION_MESSAGE);
                    txtQty_Rcv.setText("");
                }else{  //mengalikan  harga dengan Qty kedatangan
                    int angka1,angka2,hasil;
                    angka1 = Integer.parseInt(txtHarga.getText().toString());
                    angka2 = Integer.parseInt(txtQty_Rcv.getText().toString());
                    hasil = angka1 * angka2;
                    txtTotal.setText(Integer.toString(hasil));
                    tampilkan_data();
        
            }
          }
        }
    }//GEN-LAST:event_txtPassedKeyPressed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(akutansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(akutansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(akutansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(akutansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new akutansi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Kode;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtNo_Pembayaran;
    private javax.swing.JTextField txtPassed;
    private javax.swing.JTextField txtQty_Rcv;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
